import type { Metadata } from "next";
import "./globals.css";

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {process.env.NODE_ENV === "development" && (
          // <script
          //   defer
          //   src="http://localhost:3000/publisher-script.js"
          //   external-id="3"
          //   publisher-address="7pLdMe6SV289tWb3w62mbcKzEHidmwCXJrT7vzqafo7k"
          // ></script>
          <script
            defer
            src="http://localhost:3000/publisher-script.js"
            property-id="606e4aba-15dd-477c-889e-fb8cd8f5c616"
            external-id="5"
            publisher-address="Gt8ACefXe4uLYZnDEp5W4o5caL2jid5g12z68eZuJf9E"
          ></script>
        )}
        {process.env.NODE_ENV !== "development" && (
          <script
            defer
            src="https://app.getboost.so/publisher-script.js"
            property-id="3a48691b-c7a0-4249-bf31-1221a9622406"
            external-id="1"
            publisher-address="4WZYjfAwvRYGH6EgPkLFizPKDSjViLE3Pi9gauRaKRVb"
          ></script>
        )}
      </head>
      <body className={`${inter.className} bg-gray-50 antialiased`}>
        <nav className="border-b bg-white">
          <div className="container mx-auto px-4 py-4">
            <h1 className="text-2xl font-bold text-gray-900">Tech Blog</h1>
          </div>
        </nav>
        <main className="container mx-auto px-4 py-8">{children}</main>
        <footer className="border-t bg-white mt-12">
          <div className="container mx-auto px-4 py-6 text-center text-gray-600">
            © 2025 Tech Blog. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
